name: build-environment 
channels:
  - conda-forge
dependencies:
  - numpy=1.19.4
  - pillow=8.1.1
  - flask=1.1.2
  - waitress=1.4.4
  - flask_cors=3.0.9
  - matplotlib=3.3.3
  - tifffile=2020.12.4
  - imagecodecs=2020.5.30
  - zarr
  - cython
  - scikit-image
  - pyinstaller
  - altair
  - pip
  - pip:
      - git+https://github.com/labsyspharm/minerva-lib-python@master#egg=minerva-lib
      - openslide-python>=1.1.2
      - ome-types>=0.2.4
      - pandas>=1.3.2
      - opencv-python
