name: build-environment 
channels:
  - conda-forge
dependencies:
  - numpy=1.19.4
  - pillow=8.1.1
  - zarr
  - cython
  - scikit-image
  - pyinstaller
  - pip
  - pip:
      - flask>=1.1.2
      - flask_cors>=3.0.9
      - matplotlib>=3.3.3
      - ome-types>=0.2.4
      - tifffile>=2020.5.30
      - imagecodecs>=2020.5.30
      - openslide-python>=1.1.2
      - waitress>=1.4.4
      - opencv-python
