name: PyInstaller

on:
  push:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    name: Pyinstaller for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: requirements.yml
          activate-environment: build-environment
          python-version: ${{ matrix.python-version }}
      - name: OpenSlide Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          curl https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip -L -o openslide.zip
          unzip openslide.zip
          dir
          move openslide-win64-20171122\bin\* src\
      - name: OpenSlide MacOS
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          brew install openslide
      - name: Update the Minerva Story submodule
        run: |
          git submodule update --init --recursive
      - name: Copy dlls on Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          copy "%CONDA_PREFIX%\Library\bin\libcrypto-1_1-x64.dll" "%CONDA_PREFIX%\DLLs\libcrypto-1_1-x64.dll"
          copy "%CONDA_PREFIX%\Library\bin\libssl-1_1-x64.dll" "%CONDA_PREFIX%\DLLs\libssl-1_1-x64.dll"
      - name: Package Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          package_win.bat
          move dist minerva_author
          7z a minerva_author_windows.zip minerva_author
      - name: Package Mac
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          bash package_mac.sh
          mv dist minerva_author
          mv minerva_author/app minerva_author/minerva_author
          zip minerva_author_macos.zip minerva_author
      - name: Get release
        id: get_release
        uses: agners/get-draft-release@v0.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Release Windows
        if: startsWith(matrix.os,'windows')
        run: |
          gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
        env:
          FILES: minerva_author_windows.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_release.outputs.tag_name }}
      - name: Release Mac
        if: startsWith(matrix.os,'mac')
        run: |
          gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
        env:
          FILES: minerva_author_macos.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_release.outputs.tag_name }}
