name: PyInstaller

on:
  push:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.7]
    runs-on: ${{ matrix.os }}
    name: Pyinstaller for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: OpenSlide Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          curl https://github.com/openslide/openslide-winbuild/releases/download/v20171122/openslide-win64-20171122.zip -L -o openslide.zip
          unzip openslide.zip
          dir
          move openslide-win64-20171122\bin\* src\
      - name: OpenSlide MacOS
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          brew install openslide
      - name: Update the Minerva Story submodule
        run: |
          git submodule update --init --recursive
      - name: Create conda environment
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda update -q conda
          conda info -a
          conda create -q -n build-environment python=${{ matrix.python-version }} nomkl
      - name: Conda activate on Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          conda activate build-environment
      - name: Conda activate on MacOS
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          conda init bash
          conda activate build-environment
      - name: Install conda and pip dependencies
        run: |
          conda install -c conda-forge "numpy>=1.18" "matplotlib==3.2.2" cython
          pip install -r requirements.txt
          conda install scikit-image
          conda install zarr
      - name: Copy dlls on Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          copy "%CONDA_PREFIX%\Library\bin\libcrypto-1_1-x64.dll" "%CONDA_PREFIX%\DLLs\libcrypto-1_1-x64.dll"
          copy "%CONDA_PREFIX%\Library\bin\libssl-1_1-x64.dll" "%CONDA_PREFIX%\DLLs\libssl-1_1-x64.dll"
      - name: Package Windows
        if: startsWith(matrix.os,'windows')
        shell: cmd /C CALL {0}
        run: |
          package_win.bat
          move dist minerva_author
          7z a minerva_author.zip minerva_author
      - name: Package Mac
        if: startsWith(matrix.os,'mac')
        shell: bash -l {0}
        run: |
          ./package_mac.sh
          mv dist minerva_author
          mv minerva_author/app minerva_author/minerva_author
          zip minerva_author.zip minerva_author
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            minerva_author.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
